name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: API deps
        working-directory: api
        run: npm ci
      - name: WEB deps + build
        working-directory: web
        run: npm ci && npm run build
